version: 0.2
phases:
  install:
    commands:
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
  build:
    commands:
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - REPO_URI=247084108338.dkr.ecr.us-east-1.amazonaws.com/my-app
      - trivy image --exit-code 1 --severity CRITICAL,HIGH $REPO_URI:$IMAGE_TAG || exit 1
artifacts:
  files: []
